# Generated by Django 4.1.7 on 2023-05-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appForDiplom', '0002_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='content',
            field=models.JSONField(verbose_name='Дополнительный материал'),
        ),
    ]
