# Generated by Django 4.1.7 on 2023-05-17 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appForDiplom', '0006_teacher_lessons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='photo',
            new_name='video',
        ),
    ]
