# Generated by Django 4.1.7 on 2023-05-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appForDiplom', '0007_rename_photo_videos_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название теста')),
            ],
            options={
                'verbose_name': 'Название теста',
                'verbose_name_plural': 'Название тестов',
            },
        ),
        migrations.CreateModel(
            name='Test_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_T', models.IntegerField(verbose_name='ID Теста')),
                ('id_Q', models.IntegerField(verbose_name='ID Вопроса')),
            ],
            options={
                'verbose_name_plural': 'Таблица связей тесты_вопросы',
            },
        ),
    ]
