# Generated by Django 4.1.7 on 2023-05-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appForDiplom', '0008_test_test_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_Lessons_VideoANDTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_video', models.IntegerField(verbose_name='ID видео')),
                ('id_TL', models.IntegerField(verbose_name='ID преподаватель_предмет')),
            ],
            options={
                'verbose_name_plural': 'Таблица связей Преподаватель_Предмет_ВидеоИлиТест',
            },
        ),
    ]
