# Generated by Django 4.1.7 on 2023-05-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appForDiplom', '0009_teacher_lessons_videoandtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_Lessons_Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_video', models.IntegerField(verbose_name='ID теста')),
                ('id_TL', models.IntegerField(verbose_name='ID преподаватель_предмет')),
            ],
            options={
                'verbose_name_plural': 'Таблица связей Преподаватель_Предмет_Тест',
            },
        ),
        migrations.RenameModel(
            old_name='Teacher_Lessons_VideoANDTest',
            new_name='Teacher_Lessons_Video',
        ),
        migrations.AlterModelOptions(
            name='teacher_lessons_video',
            options={'verbose_name_plural': 'Таблица связей Преподаватель_Предмет_Видео'},
        ),
    ]
