# Generated by Django 4.1.7 on 2023-05-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appForDiplom', '0012_practice_question_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='content',
            field=models.TextField(default=' ', verbose_name='Задание для практики'),
        ),
    ]
