# Generated by Django 4.1.7 on 2023-06-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appForDiplom', '0014_alter_videos_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='a',
        ),
        migrations.AddField(
            model_name='question',
            name='a_1',
            field=models.TextField(default='-', verbose_name='Вариант ответ №1'),
        ),
        migrations.AddField(
            model_name='question',
            name='a_2',
            field=models.TextField(default='-', verbose_name='Вариант ответ №2'),
        ),
        migrations.AddField(
            model_name='question',
            name='a_3',
            field=models.TextField(default='-', verbose_name='Вариант ответ №3'),
        ),
        migrations.AddField(
            model_name='question',
            name='a_4',
            field=models.TextField(default='-', verbose_name='Вариант ответ №4'),
        ),
    ]
